// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rgd.proto

#ifndef PROTOBUF_INCLUDED_rgd_2eproto
#define PROTOBUF_INCLUDED_rgd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rgd_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_rgd_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_rgd_2eproto();
namespace rgd {
class JitCmd;
class JitCmdDefaultTypeInternal;
extern JitCmdDefaultTypeInternal _JitCmd_default_instance_;
class JitCmdv2;
class JitCmdv2DefaultTypeInternal;
extern JitCmdv2DefaultTypeInternal _JitCmdv2_default_instance_;
class JitReply;
class JitReplyDefaultTypeInternal;
extern JitReplyDefaultTypeInternal _JitReply_default_instance_;
class JitRequest;
class JitRequestDefaultTypeInternal;
extern JitRequestDefaultTypeInternal _JitRequest_default_instance_;
}  // namespace rgd
namespace google {
namespace protobuf {
template<> ::rgd::JitCmd* Arena::CreateMaybeMessage<::rgd::JitCmd>(Arena*);
template<> ::rgd::JitCmdv2* Arena::CreateMaybeMessage<::rgd::JitCmdv2>(Arena*);
template<> ::rgd::JitReply* Arena::CreateMaybeMessage<::rgd::JitReply>(Arena*);
template<> ::rgd::JitRequest* Arena::CreateMaybeMessage<::rgd::JitRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace rgd {

// ===================================================================

class JitCmdv2 final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rgd.JitCmdv2) */ {
 public:
  JitCmdv2();
  virtual ~JitCmdv2();

  JitCmdv2(const JitCmdv2& from);

  inline JitCmdv2& operator=(const JitCmdv2& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JitCmdv2(JitCmdv2&& from) noexcept
    : JitCmdv2() {
    *this = ::std::move(from);
  }

  inline JitCmdv2& operator=(JitCmdv2&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const JitCmdv2& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JitCmdv2* internal_default_instance() {
    return reinterpret_cast<const JitCmdv2*>(
               &_JitCmdv2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(JitCmdv2* other);
  friend void swap(JitCmdv2& a, JitCmdv2& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JitCmdv2* New() const final {
    return CreateMaybeMessage<JitCmdv2>(nullptr);
  }

  JitCmdv2* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JitCmdv2>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JitCmdv2& from);
  void MergeFrom(const JitCmdv2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JitCmdv2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .rgd.JitRequest expr = 3;
  int expr_size() const;
  void clear_expr();
  static const int kExprFieldNumber = 3;
  ::rgd::JitRequest* mutable_expr(int index);
  ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >*
      mutable_expr();
  const ::rgd::JitRequest& expr(int index) const;
  ::rgd::JitRequest* add_expr();
  const ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >&
      expr() const;

  // uint32 cmd = 1;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  ::google::protobuf::uint32 cmd() const;
  void set_cmd(::google::protobuf::uint32 value);

  // int32 test_value = 2;
  void clear_test_value();
  static const int kTestValueFieldNumber = 2;
  ::google::protobuf::int32 test_value() const;
  void set_test_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rgd.JitCmdv2)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest > expr_;
  ::google::protobuf::uint32 cmd_;
  ::google::protobuf::int32 test_value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rgd_2eproto;
};
// -------------------------------------------------------------------

class JitCmd final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rgd.JitCmd) */ {
 public:
  JitCmd();
  virtual ~JitCmd();

  JitCmd(const JitCmd& from);

  inline JitCmd& operator=(const JitCmd& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JitCmd(JitCmd&& from) noexcept
    : JitCmd() {
    *this = ::std::move(from);
  }

  inline JitCmd& operator=(JitCmd&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const JitCmd& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JitCmd* internal_default_instance() {
    return reinterpret_cast<const JitCmd*>(
               &_JitCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(JitCmd* other);
  friend void swap(JitCmd& a, JitCmd& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JitCmd* New() const final {
    return CreateMaybeMessage<JitCmd>(nullptr);
  }

  JitCmd* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JitCmd>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JitCmd& from);
  void MergeFrom(const JitCmd& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JitCmd* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 cmd = 1;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  ::google::protobuf::uint32 cmd() const;
  void set_cmd(::google::protobuf::uint32 value);

  // int32 test_value = 2;
  void clear_test_value();
  static const int kTestValueFieldNumber = 2;
  ::google::protobuf::int32 test_value() const;
  void set_test_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rgd.JitCmd)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 cmd_;
  ::google::protobuf::int32 test_value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rgd_2eproto;
};
// -------------------------------------------------------------------

class JitRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rgd.JitRequest) */ {
 public:
  JitRequest();
  virtual ~JitRequest();

  JitRequest(const JitRequest& from);

  inline JitRequest& operator=(const JitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JitRequest(JitRequest&& from) noexcept
    : JitRequest() {
    *this = ::std::move(from);
  }

  inline JitRequest& operator=(JitRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const JitRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JitRequest* internal_default_instance() {
    return reinterpret_cast<const JitRequest*>(
               &_JitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(JitRequest* other);
  friend void swap(JitRequest& a, JitRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JitRequest* New() const final {
    return CreateMaybeMessage<JitRequest>(nullptr);
  }

  JitRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JitRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JitRequest& from);
  void MergeFrom(const JitRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JitRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .rgd.JitRequest children = 5;
  int children_size() const;
  void clear_children();
  static const int kChildrenFieldNumber = 5;
  ::rgd::JitRequest* mutable_children(int index);
  ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >*
      mutable_children();
  const ::rgd::JitRequest& children(int index) const;
  ::rgd::JitRequest* add_children();
  const ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >&
      children() const;

  // string value = 4;
  void clear_value();
  static const int kValueFieldNumber = 4;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // string name = 6;
  void clear_name();
  static const int kNameFieldNumber = 6;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint32 kind = 1;
  void clear_kind();
  static const int kKindFieldNumber = 1;
  ::google::protobuf::uint32 kind() const;
  void set_kind(::google::protobuf::uint32 value);

  // uint32 boolvalue = 2;
  void clear_boolvalue();
  static const int kBoolvalueFieldNumber = 2;
  ::google::protobuf::uint32 boolvalue() const;
  void set_boolvalue(::google::protobuf::uint32 value);

  // uint32 bits = 3;
  void clear_bits();
  static const int kBitsFieldNumber = 3;
  ::google::protobuf::uint32 bits() const;
  void set_bits(::google::protobuf::uint32 value);

  // uint32 index = 7;
  void clear_index();
  static const int kIndexFieldNumber = 7;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // uint32 label = 8;
  void clear_label();
  static const int kLabelFieldNumber = 8;
  ::google::protobuf::uint32 label() const;
  void set_label(::google::protobuf::uint32 value);

  // uint32 hash = 9;
  void clear_hash();
  static const int kHashFieldNumber = 9;
  ::google::protobuf::uint32 hash() const;
  void set_hash(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:rgd.JitRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest > children_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 kind_;
  ::google::protobuf::uint32 boolvalue_;
  ::google::protobuf::uint32 bits_;
  ::google::protobuf::uint32 index_;
  ::google::protobuf::uint32 label_;
  ::google::protobuf::uint32 hash_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rgd_2eproto;
};
// -------------------------------------------------------------------

class JitReply final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rgd.JitReply) */ {
 public:
  JitReply();
  virtual ~JitReply();

  JitReply(const JitReply& from);

  inline JitReply& operator=(const JitReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JitReply(JitReply&& from) noexcept
    : JitReply() {
    *this = ::std::move(from);
  }

  inline JitReply& operator=(JitReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const JitReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JitReply* internal_default_instance() {
    return reinterpret_cast<const JitReply*>(
               &_JitReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(JitReply* other);
  friend void swap(JitReply& a, JitReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JitReply* New() const final {
    return CreateMaybeMessage<JitReply>(nullptr);
  }

  JitReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JitReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JitReply& from);
  void MergeFrom(const JitReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JitReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:rgd.JitReply)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rgd_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JitCmdv2

// uint32 cmd = 1;
inline void JitCmdv2::clear_cmd() {
  cmd_ = 0u;
}
inline ::google::protobuf::uint32 JitCmdv2::cmd() const {
  // @@protoc_insertion_point(field_get:rgd.JitCmdv2.cmd)
  return cmd_;
}
inline void JitCmdv2::set_cmd(::google::protobuf::uint32 value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitCmdv2.cmd)
}

// int32 test_value = 2;
inline void JitCmdv2::clear_test_value() {
  test_value_ = 0;
}
inline ::google::protobuf::int32 JitCmdv2::test_value() const {
  // @@protoc_insertion_point(field_get:rgd.JitCmdv2.test_value)
  return test_value_;
}
inline void JitCmdv2::set_test_value(::google::protobuf::int32 value) {
  
  test_value_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitCmdv2.test_value)
}

// repeated .rgd.JitRequest expr = 3;
inline int JitCmdv2::expr_size() const {
  return expr_.size();
}
inline void JitCmdv2::clear_expr() {
  expr_.Clear();
}
inline ::rgd::JitRequest* JitCmdv2::mutable_expr(int index) {
  // @@protoc_insertion_point(field_mutable:rgd.JitCmdv2.expr)
  return expr_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >*
JitCmdv2::mutable_expr() {
  // @@protoc_insertion_point(field_mutable_list:rgd.JitCmdv2.expr)
  return &expr_;
}
inline const ::rgd::JitRequest& JitCmdv2::expr(int index) const {
  // @@protoc_insertion_point(field_get:rgd.JitCmdv2.expr)
  return expr_.Get(index);
}
inline ::rgd::JitRequest* JitCmdv2::add_expr() {
  // @@protoc_insertion_point(field_add:rgd.JitCmdv2.expr)
  return expr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >&
JitCmdv2::expr() const {
  // @@protoc_insertion_point(field_list:rgd.JitCmdv2.expr)
  return expr_;
}

// -------------------------------------------------------------------

// JitCmd

// uint32 cmd = 1;
inline void JitCmd::clear_cmd() {
  cmd_ = 0u;
}
inline ::google::protobuf::uint32 JitCmd::cmd() const {
  // @@protoc_insertion_point(field_get:rgd.JitCmd.cmd)
  return cmd_;
}
inline void JitCmd::set_cmd(::google::protobuf::uint32 value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitCmd.cmd)
}

// int32 test_value = 2;
inline void JitCmd::clear_test_value() {
  test_value_ = 0;
}
inline ::google::protobuf::int32 JitCmd::test_value() const {
  // @@protoc_insertion_point(field_get:rgd.JitCmd.test_value)
  return test_value_;
}
inline void JitCmd::set_test_value(::google::protobuf::int32 value) {
  
  test_value_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitCmd.test_value)
}

// -------------------------------------------------------------------

// JitRequest

// uint32 kind = 1;
inline void JitRequest::clear_kind() {
  kind_ = 0u;
}
inline ::google::protobuf::uint32 JitRequest::kind() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.kind)
  return kind_;
}
inline void JitRequest::set_kind(::google::protobuf::uint32 value) {
  
  kind_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitRequest.kind)
}

// uint32 boolvalue = 2;
inline void JitRequest::clear_boolvalue() {
  boolvalue_ = 0u;
}
inline ::google::protobuf::uint32 JitRequest::boolvalue() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.boolvalue)
  return boolvalue_;
}
inline void JitRequest::set_boolvalue(::google::protobuf::uint32 value) {
  
  boolvalue_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitRequest.boolvalue)
}

// uint32 bits = 3;
inline void JitRequest::clear_bits() {
  bits_ = 0u;
}
inline ::google::protobuf::uint32 JitRequest::bits() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.bits)
  return bits_;
}
inline void JitRequest::set_bits(::google::protobuf::uint32 value) {
  
  bits_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitRequest.bits)
}

// string value = 4;
inline void JitRequest::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JitRequest::value() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.value)
  return value_.GetNoArena();
}
inline void JitRequest::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rgd.JitRequest.value)
}
#if LANG_CXX11
inline void JitRequest::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rgd.JitRequest.value)
}
#endif
inline void JitRequest::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rgd.JitRequest.value)
}
inline void JitRequest::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rgd.JitRequest.value)
}
inline ::std::string* JitRequest::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:rgd.JitRequest.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JitRequest::release_value() {
  // @@protoc_insertion_point(field_release:rgd.JitRequest.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JitRequest::set_allocated_value(::std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:rgd.JitRequest.value)
}

// repeated .rgd.JitRequest children = 5;
inline int JitRequest::children_size() const {
  return children_.size();
}
inline void JitRequest::clear_children() {
  children_.Clear();
}
inline ::rgd::JitRequest* JitRequest::mutable_children(int index) {
  // @@protoc_insertion_point(field_mutable:rgd.JitRequest.children)
  return children_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >*
JitRequest::mutable_children() {
  // @@protoc_insertion_point(field_mutable_list:rgd.JitRequest.children)
  return &children_;
}
inline const ::rgd::JitRequest& JitRequest::children(int index) const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.children)
  return children_.Get(index);
}
inline ::rgd::JitRequest* JitRequest::add_children() {
  // @@protoc_insertion_point(field_add:rgd.JitRequest.children)
  return children_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::rgd::JitRequest >&
JitRequest::children() const {
  // @@protoc_insertion_point(field_list:rgd.JitRequest.children)
  return children_;
}

// string name = 6;
inline void JitRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JitRequest::name() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.name)
  return name_.GetNoArena();
}
inline void JitRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rgd.JitRequest.name)
}
#if LANG_CXX11
inline void JitRequest::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rgd.JitRequest.name)
}
#endif
inline void JitRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rgd.JitRequest.name)
}
inline void JitRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rgd.JitRequest.name)
}
inline ::std::string* JitRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:rgd.JitRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JitRequest::release_name() {
  // @@protoc_insertion_point(field_release:rgd.JitRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JitRequest::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:rgd.JitRequest.name)
}

// uint32 index = 7;
inline void JitRequest::clear_index() {
  index_ = 0u;
}
inline ::google::protobuf::uint32 JitRequest::index() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.index)
  return index_;
}
inline void JitRequest::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitRequest.index)
}

// uint32 label = 8;
inline void JitRequest::clear_label() {
  label_ = 0u;
}
inline ::google::protobuf::uint32 JitRequest::label() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.label)
  return label_;
}
inline void JitRequest::set_label(::google::protobuf::uint32 value) {
  
  label_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitRequest.label)
}

// uint32 hash = 9;
inline void JitRequest::clear_hash() {
  hash_ = 0u;
}
inline ::google::protobuf::uint32 JitRequest::hash() const {
  // @@protoc_insertion_point(field_get:rgd.JitRequest.hash)
  return hash_;
}
inline void JitRequest::set_hash(::google::protobuf::uint32 value) {
  
  hash_ = value;
  // @@protoc_insertion_point(field_set:rgd.JitRequest.hash)
}

// -------------------------------------------------------------------

// JitReply

// string message = 1;
inline void JitReply::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JitReply::message() const {
  // @@protoc_insertion_point(field_get:rgd.JitReply.message)
  return message_.GetNoArena();
}
inline void JitReply::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rgd.JitReply.message)
}
#if LANG_CXX11
inline void JitReply::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rgd.JitReply.message)
}
#endif
inline void JitReply::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rgd.JitReply.message)
}
inline void JitReply::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rgd.JitReply.message)
}
inline ::std::string* JitReply::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:rgd.JitReply.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JitReply::release_message() {
  // @@protoc_insertion_point(field_release:rgd.JitReply.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JitReply::set_allocated_message(::std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:rgd.JitReply.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rgd

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_rgd_2eproto
